apiVersion: batch/v1
kind: Job
metadata:
  name: orders-topic
  namespace: kafka
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kafka-topics
          image: apache/kafka:3.7.2
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -ec
            - |
              /opt/kafka/bin/kafka-topics.sh \
                --bootstrap-server kafka.kafka.svc.cluster.local:9092 \
                --create \
                --if-not-exists \
                --topic orders \
                --partitions 6 \
                --replication-factor 1
